package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 28 10:09:48 GMT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ViewObjImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ViewObjImpl() {
    }
}

